//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_tbl
    {
        public int OrderId { get; set; }
        public Nullable<int> Order_FK_Product { get; set; }
        public Nullable<int> order_FK_Invoice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<double> OrderBill { get; set; }
        public Nullable<int> OrderUnitprice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
